scripts:
  main.js:
    # - node_modules/animation-frame/AnimationFrame.js
    # - node_modules/float-labels.js/src/float-labels.js
    # - node_modules/javascript-flex-images/flex-images.js
    # - +/js/helpers.js
    - +/js/main.js
  # customizer.js:
  #   - +/js/customizer.js
modernizr:
  options:
    - setClasses
  feature-detects:
    - css/animations
    - css/transforms
watch:
  js: +/js/**/*.js
  scss: +/scss/**/*.scss
  img: +/img/**/*
  php:
    - templates/**/*.php
    - '*.php'
dest:
  js: assets/js/
  css: assets/css/
  img: assets/img/
  lang: languages/
browsersync:
  proxy: wordpress.test
language:
  domain: castor
  translator: Paul Ryley <paul@geminilabs.io>
  team: Gemini Labs <support@geminilabs.io>
